service_name: go-micro-demo

app:

db:
  # 这里支持多库配置
  default:
    database: demo_db
    dbType: mysql
    host: 127.0.0.1
    password: 123456
    port: 3306
    userName: root
redis:
  address: 127.0.0.1:6379
  dbNum: 0
  password:
  readTimeout: 500
